version: "3.9"

services:
  db:
    image: postgres:15
    container_name: devops-tracker-db
    environment:
      POSTGRES_USER: devops
      POSTGRES_PASSWORD: devops
      POSTGRES_DB: tracker
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U devops -d tracker"]
      interval: 10s
      retries: 5

  backend:
    build: ./backend
    container_name: devops-tracker-backend
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql://devops:devops@db:5432/tracker
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app

volumes:
  postgres_data:
